DROP DATABASE IF EXISTS ManutenzioneIT;
CREATE DATABASE ManutenzioneIT;
USE ManutenzioneIT;

-- Tabella UTENTE
CREATE TABLE UTENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    NOME VARCHAR(255),
    COGNOME VARCHAR(255),
    RUOLO VARCHAR(255)
);

-- Tabella URGENZA
CREATE TABLE URGENZA (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TIPOURGENZA VARCHAR(255)
);

-- Tabella RICHIESTA
CREATE TABLE RICHIESTA (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    DATA_INVIA DATE,
    DESCRIZIONE TEXT,
    URGENZA_ID INT,
    STATO VARCHAR(255) DEFAULT 'In attesa',
    DATA_CHIUSURA DATETIME NULL,
    SCREENSHOT_PATH VARCHAR(255), 
    FOREIGN KEY (URGENZA_ID) REFERENCES URGENZA(ID)
);

-- Inserimento utenti di esempio
INSERT INTO UTENTE (USERNAME, PASSWORD, NOME, COGNOME, RUOLO)
VALUES 
('admin', '1a01b60f1adf59e6cc9349e49d68d6b9', 'Marcello', 'Clivati', 'TITOLARE'),
('silviaIT', '1a01b60f1adf59e6cc9349e49d68d6b9', 'Silvia', 'Arnoldi', 'IT');

-- Inserimento livelli di urgenza
INSERT INTO URGENZA (TIPOURGENZA) 
VALUES 
('Bassa - Non blocca il lavoro'),
('Media - Causa rallentamenti'),
('Alta - Blocco totale del lavoro');